### ISSUE TITLE
Investigate bookList not updating automatically after inserting a new book

### ISSUE THREAD

**Issue by swd1tn002** [LibraryProjectGroup/library-project-frontend#172]
While reviewing the pull request for #164 we noticed random failures in robot tests after inserting a new book. The results could be verified outside of robot tests, too.

The issue is that after a book is inserted into the database and the book list is updated, the new book does not appear. Instead, the server returns a 304 response with outdated list of books. Insertion appears to happen correctly, as by refreshing the page the new book appears.

The issue likely has something to do with the LRU cache in mysql2, which is not that well documented. The npm page https://www.npmjs.com/package/mysql2 states "If you execute same statement again, it will be picked from a LRU cache which will save query preparation time and give better performance".

Looks like this is a cache invalidation issue. There are also others facing similar issue: https://github.com/sidorares/node-mysql2/issues/929

**Comment by Lauri-Iivarinen** [comment]
As mentioned in the similar issue link, the problem seems to boil down to transactions, however adding book or fetching all books doest not use transactions, only OIDC authentication uses transactions so the core issue might be in the authentication. When the book is added and then in the same function (backend) all books are fetched for logging purposes the newest addition is already in the list before the successful response has even been returned to frontend. Potential solution would be to send a list of all books in the return statement after adding a new book, however this might mess up pagination on the page so it would require extra steps in frontend.

**Comment by swd1tn002** [comment]
Great job @Lauri-Iivarinen ! 

The potential solution would likely be feasible, but as you said, it would require some changes to both the backend and frontend and would likely complicate the app even more. I'm also concerned that we will find similar issues in the future with any feature we develop that would require adding data and updating the view.

I happened to notice that we are using an outdated version of the mysql2 package. Our version is 2.3.3 and the latest is 3.6.1: https://github.com/LibraryProjectGroup/library-project-backend/blob/0c6a8456f33eaccf4bad4b9c439c34442240ab4c/package.json#L24-L25 https://www.npmjs.com/package/mysql2?activeTab=versions. Maybe we should first try to update the dependency and see if the library was to blame and has been fixed? 

Also, there seems to be a `mysql` dependency in our package.json that probably should be removed...

**Comment by MLorenz04** [comment]
Hi! Absolutely random person from internet asking for help with the absolutely exact issue. Have you figured out the problem? Is really the only solution to not use transactions?

**Comment by Lauri-Iivarinen** [comment]
Hello. Unfortunately we did not resolve the issue but since the problem was quite small for this project we merely bypassed it by changing how backend returns data in couple occasions.

**Comment by MLorenz04** [comment]
Hah, thanks for info! I was able to solve it by adding one more query  - "SELECT 1 WHERE 1 = 0",  which triggered LRU to cache this specific query and not the one i needed to. Since then, i only got right data.
