### ISSUE TITLE
Filtering book list based on the office

### ISSUE THREAD

**Issue by Lauri-Iivarinen** [LibraryProjectGroup/library-project-frontend#190]
Add filter allowing users to sort/filter books based on the office the book is located at.

- [x] Admin page

- [x] Book list page (homepage)

**Comment by Lauri-Iivarinen** [comment]
Clarification: Admin page had already a sorting mechanism but did not work for office location. We could create a new filter/sorting mechanism for Book list page as well.

**Comment by jounijoh** [comment]
Added 'Sort by' (selected value) and 'Filter by office' dropdown buttons.  


![Image](https://github.com/LibraryProjectGroup/library-project-frontend/assets/95469212/687f40d1-b4f5-49b1-8764-19e8b81dfc39)
