### ISSUE TITLE
identifying issues in the current frontend code

### ISSUE THREAD

**Issue by AnjaMis** [LibraryProjectGroup/library-project-frontend#25]
- [x] Using .css stylesheet instead of the inline styling
- [x] going through the code manually
- [x] fixing the file structure
- [x] every page needs to have its own file (separate from the components)
- [x] removing redundant code
- [x] create components for the code that appears more than once in any of the files
- [ ] checking if a good LINTER for React exists (?)

**Comment by Eelii** [comment]
MUI components are styled using sx prop, so as a halfway solution I moved most sx objects to a separate sxStyles file.
