### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by Eelii** [LibraryProjectGroup/library-project-frontend#36]
- [x] Listing all user profiles
- [x] Sending a DELETE request with user data to backend 
- [x] Verification when deleting a user
- [x] notifications/table of users who breached the loan period

**Comment by AnjaMis** [comment]
Can there also be a view of the book requests made by users? Also a little checkbox or something to mark those requests as "done"? :)

**Comment by Eelii** [comment]
Book requests with current status added 👍

**Comment by julisod** [comment]
I know this is marked as done by the old group, but a verification when deleting a user might be a good thing to have.
